CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(200) NOT NULL,
    CORREO_ELECTRONICO VARCHAR2(255) NOT NULL UNIQUE,
    CONTRASENA VARCHAR2(500) NOT NULL, --One-way hash -https://bcrypt.online/- contraseña del usuario
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FECHA_ULTIMO_ACCESO DATE 
);

CREATE TABLE IF NOT EXISTS POLIZAS (
    NUMERO_POLIZA VARCHAR2(50) PRIMARY KEY,
    MODALIDAD VARCHAR2(100) NOT NULL,
    PRIMA NUMBER(10,2) NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IF NOT EXISTS IDX_POLIZAS_USUARIO ON POLIZAS(ID_USUARIO);
