INSERT INTO USUARIOS (NOMBRE, APELLIDOS, CORREO_ELECTRONICO, CONTRASENA) VALUES ('Nombre1','Apellido1','Email1@example.com','$2y$10$vMPfMHDMPUWXw48L/1uROuSTerucLj0jopR38NXv3P8LqfFe.XSsy');
INSERT INTO USUARIOS (NOMBRE, APELLIDOS, CORREO_ELECTRONICO, CONTRASENA) VALUES ('Nombre2','Apellido2','Email2@example.com','$2y$10$/xp/a94Zowr8UXulDLJdUOwaVkaOpsQWyvyvzxIsnkSMVImLc2286');

INSERT INTO POLIZAS (NUMERO_POLIZA, MODALIDAD, PRIMA, ID_USUARIO) VALUES ('POL1', 'Todo Riesgo', 520.50, 1);
INSERT INTO POLIZAS (NUMERO_POLIZA, MODALIDAD, PRIMA, ID_USUARIO) VALUES ('POL2', 'Terceros', 310.75, 2);
INSERT INTO POLIZAS (NUMERO_POLIZA, MODALIDAD, PRIMA, ID_USUARIO) VALUES ('POL3', 'Viaje', 95.30, 2);